{% set version = "0.2.1.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-umap
  version: {{ version|replace("-", "_") }}

source:
  fn: umap_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/umap_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/umap/umap_{{ version }}.tar.gz
  sha256: c2ef42ae14bd0df16f2eadcb24d84eddaa3658f17db9c37a66702e61e8ee1e41

build:
  merge_build_host: True  # [win]
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed  # [win]
    - {{posix}}coreutils  # [win]
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rspectra
    - r-rcpp >=0.12.6
    - r-reticulate

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rspectra
    - r-rcpp >=0.12.6
    - r-reticulate

test:
  commands:
    - $R -e "library('umap')"           # [not win]
    - "\"%R%\" -e \"library('umap')\""  # [win]

about:
  home: https://github.com/tkonopka/umap
  license: MIT
  summary: Uniform manifold approximation and projection is a technique for dimension reduction.
    The algorithm was described by McInnes and Healy (2018) in <arXiv:1802.03426>. This
    package provides an interface for two implementations. One is written from scratch,
    including components for nearest-neighbor search and for embedding. The second implementation
    is a wrapper for 'python' package 'umap-learn' (requires separate installation,
    see vignette for more details).
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - apcamargo
