travis:
  secure:
    BINSTAR_TOKEN: ZZRHmo5ZhcCWc3X5qM3UdgTlvXLtEyFGo13Dt9+Wg876Ct96ucAr8LItPS0aV+L2y7hn1pJJv4yxEAM7Zv4ls/fKwH88Cc74YZDbuFU99yk/gEeFYMkrz9mOHlZ5bEl1Ba3bb3H/KYOk3+K3AJhvRMsYfMqdW0m8p79UOt7w0Drqz8/7UJ/vRKuWYzckYkr5/JwaRBI7YkbuiTvX9ZsFwSsn8w6D7F+yl3vNys2kWlkrpZhivp5r2cZZa8EC1PxJSQsz+vaRC607Xb28KS3fLPHpVFQlMVyQ24XA21Nu1fgKjC4w00xLRQz8kGEBoJqE2Hj8ovY0NgNyx5ZXvvJdDrw+RzSiqqVCGTXDNBY0myyz5/hgVvzMF4NDEvqKZKbu30u8y6fIr+NVFc1BL34H1yzuJEdUrOZojJqvL46vHp/GDZtj5rBL/5PD8S54cbggIeetCBZZ6dLro/cDECZ1Jwt37LVFtq/L5ppofQIa50tvWhCIWVYa3R3Kky5300hB0IdPifO0q24bqwukRXGe52/0JInoJ3ktcw6Ryz7XzSbdQ0v2Q8qioFl/gOdxBnJAohP/tdmwzQTfiXyWQuDWRbrC51R4o8rv1q3ilgv2ZU4UFiBLS+CFay0CcE/uHYN/36sK6lyzE2zUm1eLtr+K3+kLFQGA/eT689TX92chUt8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
