appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: A3BydqJ3T86BMTer+4x+A9XdHD3MqPUl5bZk3V9Cbf12jwNCXm/LJVlPjwKWrMmCrGntF70evDBJTf/E22TplfghpsPg2a/Dn6GBsLIcBLwtnU69nzMX+Db/w38SWmO+Q7ImsdYboP56ePfZyS7HqNksF2GZe2TCms3/jG8FGdU2VUJhvdJRMudNv0ger7NOnH4SoLXWMtBVl4wASbKOuWZceOt1gES0i6L9q+xRXjnODHPsFVVCarjngYaEW5a72nUk23mxHbjVyS8Ptsnk7JaPq6SV6i9l/wipTiiTTsoz004hQsjIL1SaH3ARs88N+eQtO7vG1GUqVwh2ISmVFA947029OYPIZ7yIie8eHC1FU79sxsidI6M3rtdZNYVxetZAb9zjy5dwBgZ5VDbUeXNupC+FTbgJWOcpYLYqamdB/RAp0KUvUf2VHU0rv5RZ3djCwVMu9cSJ9FV1xODspdRnUnS0AxEDxk8CwCw5Xmcw+4rkUrh227P1ext/fTy1g0pH3BOdlClI4LRSnLwzJvqb4bY3QBD374PphoM+AgfdVxZP+Mr3JjsvHN1QgBoacqry24Yik6A89PzBEaEunprlN+x7m3RPGVacvrXYFRR+IltTLTv96YbhHjLJDpcNstURRAZxol2sdAiABnTT4jE2IAzrM13IB2/UbkAcBoE=}
